---

- name: Install Percona XtraDB Cluster server
  apt: pkg={{ item }} 
       state=present
  with_items:
    - percona-xtradb-cluster-server-5.6
    - python-mysqldb
    - xinetd
    - telnet

- name: Copy the helper script 
  copy: src=usr/local/bin/mysql_run.sh 
        dest=/usr/local/bin/mysql_run.sh 
        mode=0755
