---

- name: Configure Percona XtraDB Cluster server
  template: src=etc/mysql/my.cnf.j2
            dest=/etc/mysql/my.cnf
            mode=0640 owner=mysql group=root
  notify: restart mysql 
  when: bootstrap_check.stdout == "bootstrap"
