---

- name: Copy the modified init script 
  copy: src=etc/init.d/mysql
        dest=/etc/init.d/mysql
        mode=0755

- name: Copy the helper script 
  copy: src=usr/local/bin/start_services.sh 
        dest=/usr/local/bin/entrypoint.sh 
        mode=0755

- name: Configure Percona XtraDB Cluster server
  template: src=etc/mysql/my.cnf.j2
            dest=/etc/mysql/my.cnf
            mode=0640 owner=mysql group=root
  notify: restart mysql 
  when: bootstrap_check.stdout == "bootstrap"
